apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgis
spec:
  images:
    - major: 17
      image: ghcr.io/atomised/postgis:17-3.5-90@sha256:daefa017822fa36d0c732fc6b245f65a49b27ede73b4225dfa8b1902a54107a1
